# Gradle settings
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Environment properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.10-beta
neo_version_range=[26.1.2,)

# Dependency versions
jei_version=29.5.0.26
jade_version=26.0.9+neoforge

# Mod properties
mod_id=nostalgictrees
mod_name=Nostalgic Trees
mod_license=MIT
mod_version=0.2.0+mc26.1.2
mod_group_id=com.nostalgictrees
mod_authors=Nostalgic-am
mod_description=Bring back pre-1.13 tree behavior with resource saplings, advanced beehives, drying racks, and more.
